spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    user: sa
    password:
    baseline-version: 0
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
