-- course 데이터 입력
insert into course values(1, 1, 'Introduction to Data Analysis');
insert into course values(2, 1, 'Statistical Computing with R');
insert into course values(3, 1, 'Introduction to data Science');
insert into course values(4, 1, 'introduction to statistical thinking)');
insert into course values(5, 1, 'Statistical Analysis Using Excel');
insert into course values(6, 1, 'Introduction to Opinion Polls');
insert into course values(7, 1, 'Introduction to Statistics');
insert into course values(8, 1, 'introduction to official statistics');
insert into course values(9, 1, 'Python and R');
insert into course values(10, 1, 'Probability Concept and Applications');
insert into course values(11, 1, 'Data Visualization');
insert into course values(12, 1, 'regression models');
insert into course values(13, 1, 'quality management');
insert into course values(14, 1, 'survey Research Methodology');
insert into course values(15, 1, 'Statistical Package');
insert into course values(16, 1, 'public health data Analysis');
insert into course values(17, 1, 'Sampling Technique');
insert into course values(18, 1, 'Experimental Designs');
insert into course values(19, 2, 'data processing and application');
insert into course values(20, 2, 'concepts and controversies of statistics');
insert into course values(21, 2, 'Reliability Engineering');
insert into course values(22, 2, 'Forecasting Methods and its Applications');
insert into course values(23, 2, 'Multivariate Data Analysis');
insert into course values(24, 2, 'data mining');
insert into course values(25, 2, 'Introduction to Statistical Deep Learning)');
insert into course values(26, 2, 'Unstructured Data Analytics');
insert into course values(27, 2, 'bioinfomatics');
insert into course values(28, 3, 'Literature and Society in Africa and the Caribbean');
insert into course values(29, 3, 'Contemporary Issues in African Studies');
insert into course values(30, 3, 'Introduction to International and Comparative Education');
insert into course values(31, 3, 'The Egyptians ');
insert into course values(32, 3, 'Democracy, Development, and the Rule of Law');
insert into course values(33, 3, 'Beginning Amharic, First Quarter');


-- section 데이터 입력
insert into section values(1, 1);
insert into section values(2, 1);
insert into section values(3, 1);
insert into section values(4, 2);
insert into section values(5, 2);
insert into section values(6, 2);
insert into section values(7, 3);
insert into section values(8, 3);
insert into section values(9, 3);
insert into section values(10, 4);
insert into section values(11, 4);
insert into section values(12, 4);
insert into section values(13, 5);
insert into section values(14, 5);
insert into section values(15, 5);
insert into section values(16, 6);
insert into section values(17, 6);
insert into section values(18, 6);
insert into section values(19, 7);
insert into section values(20, 7);
insert into section values(21, 7);
insert into section values(22, 8);
insert into section values(23, 8);
insert into section values(24, 8);
insert into section values(25, 9);
insert into section values(26, 9);
insert into section values(27, 9);
insert into section values(28, 10);
insert into section values(29, 10);
insert into section values(30, 10);
insert into section values(31, 11);
insert into section values(32, 11);
insert into section values(33, 11);
insert into section values(34, 12);
insert into section values(35, 12);
insert into section values(36, 12);
insert into section values(37, 13);
insert into section values(38, 13);
insert into section values(39, 13);
insert into section values(40, 14);
insert into section values(41, 14);
insert into section values(42, 14);
insert into section values(43, 15);
insert into section values(44, 15);
insert into section values(45, 15);
insert into section values(46, 16);
insert into section values(47, 16);
insert into section values(48, 16);
insert into section values(49, 17);
insert into section values(50, 17);
insert into section values(51, 17);
insert into section values(52, 18);
insert into section values(53, 18);
insert into section values(54, 18);
insert into section values(55, 19);
insert into section values(56, 19);
insert into section values(57, 19);
insert into section values(58, 20);
insert into section values(59, 20);
insert into section values(60, 20);
insert into section values(61, 21);
insert into section values(62, 21);
insert into section values(63, 21);
insert into section values(64, 22);
insert into section values(65, 22);
insert into section values(66, 22);
insert into section values(67, 23);
insert into section values(68, 23);
insert into section values(69, 23);
insert into section values(70, 24);
insert into section values(71, 24);
insert into section values(72, 24);
insert into section values(73, 25);
insert into section values(74, 25);
insert into section values(75, 25);
insert into section values(76, 26);
insert into section values(77, 26);
insert into section values(78, 26);
insert into section values(79, 27);
insert into section values(80, 27);
insert into section values(81, 27);
insert into section values(82, 28);
insert into section values(83, 28);
insert into section values(84, 28);
insert into section values(85, 29);
insert into section values(86, 29);
insert into section values(87, 29);
insert into section values(88, 30);
insert into section values(89, 30);
insert into section values(90, 30);
insert into section values(91, 31);
insert into section values(92, 31);
insert into section values(93, 31);
insert into section values(94, 32);
insert into section values(95, 32);
insert into section values(96, 32);
insert into section values(97, 33);
insert into section values(98, 33);
insert into section values(99, 33);

-- section_time 데이터 입력
insert into section_time values(1, 'ONE', 2, 'MONDAY', 1);
insert into section_time values(2, 'TWO', 2, 'TUESDAY', 2);
insert into section_time values(3, 'THREE', 2, 'WEDNESDAY', 3);
insert into section_time values(4, 'FOUR', 2, 'THURSDAY', 4);
insert into section_time values(5, 'FIVE', 2, 'FRIDAY', 5);
insert into section_time values(6, 'SIX', 2, 'MONDAY', 6);
insert into section_time values(7, 'SEVEN', 2, 'TUESDAY', 7);
insert into section_time values(8, 'ONE', 2, 'WEDNESDAY', 8);
insert into section_time values(9, 'TWO', 2, 'THURSDAY', 9);
insert into section_time values(10, 'THREE', 2, 'FRIDAY', 10);
insert into section_time values(11, 'FOUR', 2, 'MONDAY', 11);
insert into section_time values(12, 'FIVE', 2, 'TUESDAY', 12);
insert into section_time values(13, 'SIX', 2, 'WEDNESDAY', 13);
insert into section_time values(14, 'SEVEN', 2, 'THURSDAY', 14);
insert into section_time values(15, 'ONE', 2, 'FRIDAY', 15);
insert into section_time values(16, 'TWO', 2, 'MONDAY', 16);
insert into section_time values(17, 'THREE', 2, 'TUESDAY', 17);
insert into section_time values(18, 'FOUR', 2, 'WEDNESDAY', 18);
insert into section_time values(19, 'FIVE', 2, 'THURSDAY', 19);
insert into section_time values(20, 'SIX', 2, 'FRIDAY', 20);
insert into section_time values(21, 'SEVEN', 2, 'MONDAY', 21);
insert into section_time values(22, 'ONE', 2, 'TUESDAY', 22);
insert into section_time values(23, 'TWO', 2, 'WEDNESDAY', 23);
insert into section_time values(24, 'THREE', 2, 'THURSDAY', 24);
insert into section_time values(25, 'FOUR', 2, 'FRIDAY', 25);
insert into section_time values(26, 'FIVE', 2, 'MONDAY', 26);
insert into section_time values(27, 'SIX', 2, 'TUESDAY', 27);
insert into section_time values(28, 'SEVEN', 2, 'WEDNESDAY', 28);
insert into section_time values(29, 'ONE', 2, 'THURSDAY', 29);
insert into section_time values(30, 'TWO', 2, 'FRIDAY', 30);
insert into section_time values(31, 'THREE', 2, 'MONDAY', 31);
insert into section_time values(32, 'FOUR', 2, 'TUESDAY', 32);
insert into section_time values(33, 'FIVE', 2, 'WEDNESDAY', 33);
insert into section_time values(34, 'SIX', 2, 'THURSDAY', 34);
insert into section_time values(35, 'SEVEN', 2, 'FRIDAY', 35);
insert into section_time values(36, 'ONE', 2, 'MONDAY', 36);
insert into section_time values(37, 'TWO', 2, 'TUESDAY', 37);
insert into section_time values(38, 'THREE', 2, 'WEDNESDAY', 38);
insert into section_time values(39, 'FOUR', 2, 'THURSDAY', 39);
insert into section_time values(40, 'FIVE', 2, 'FRIDAY', 40);
insert into section_time values(41, 'SIX', 2, 'MONDAY', 41);
insert into section_time values(42, 'SEVEN', 2, 'TUESDAY', 42);
insert into section_time values(43, 'ONE', 2, 'WEDNESDAY', 43);
insert into section_time values(44, 'TWO', 2, 'THURSDAY', 44);
insert into section_time values(45, 'THREE', 2, 'FRIDAY', 45);
insert into section_time values(46, 'FOUR', 2, 'MONDAY', 46);
insert into section_time values(47, 'FIVE', 2, 'TUESDAY', 47);
insert into section_time values(48, 'SIX', 2, 'WEDNESDAY', 48);
insert into section_time values(49, 'SEVEN', 2, 'THURSDAY', 49);
insert into section_time values(50, 'ONE', 2, 'FRIDAY', 50);
insert into section_time values(51, 'TWO', 2, 'MONDAY', 51);
insert into section_time values(52, 'THREE', 2, 'TUESDAY', 52);
insert into section_time values(53, 'FOUR', 2, 'WEDNESDAY', 53);
insert into section_time values(54, 'FIVE', 2, 'THURSDAY', 54);
insert into section_time values(55, 'SIX', 2, 'FRIDAY', 55);
insert into section_time values(56, 'SEVEN', 2, 'MONDAY', 56);
insert into section_time values(57, 'ONE', 2, 'TUESDAY', 57);
insert into section_time values(58, 'TWO', 2, 'WEDNESDAY', 58);
insert into section_time values(59, 'THREE', 2, 'THURSDAY', 59);
insert into section_time values(60, 'FOUR', 2, 'FRIDAY', 60);
insert into section_time values(61, 'FIVE', 2, 'MONDAY', 61);
insert into section_time values(62, 'SIX', 2, 'TUESDAY', 62);
insert into section_time values(63, 'SEVEN', 2, 'WEDNESDAY', 63);
insert into section_time values(64, 'ONE', 2, 'THURSDAY', 64);
insert into section_time values(65, 'TWO', 2, 'FRIDAY', 65);
insert into section_time values(66, 'THREE', 2, 'MONDAY', 66);
insert into section_time values(67, 'FOUR', 2, 'TUESDAY', 67);
insert into section_time values(68, 'FIVE', 2, 'WEDNESDAY', 68);
insert into section_time values(69, 'SIX', 2, 'THURSDAY', 69);
insert into section_time values(70, 'SEVEN', 2, 'FRIDAY', 70);
insert into section_time values(71, 'ONE', 2, 'MONDAY', 71);
insert into section_time values(72, 'TWO', 2, 'TUESDAY', 72);
insert into section_time values(73, 'THREE', 2, 'WEDNESDAY', 73);
insert into section_time values(74, 'FOUR', 2, 'THURSDAY', 74);
insert into section_time values(75, 'FIVE', 2, 'FRIDAY', 75);
insert into section_time values(76, 'SIX', 2, 'MONDAY', 76);
insert into section_time values(77, 'SEVEN', 2, 'TUESDAY', 77);
insert into section_time values(78, 'ONE', 2, 'WEDNESDAY', 78);
insert into section_time values(79, 'TWO', 2, 'THURSDAY', 79);
insert into section_time values(80, 'THREE', 2, 'FRIDAY', 80);
insert into section_time values(81, 'FOUR', 2, 'MONDAY', 81);
insert into section_time values(82, 'FIVE', 2, 'TUESDAY', 82);
insert into section_time values(83, 'SIX', 2, 'WEDNESDAY', 83);
insert into section_time values(84, 'SEVEN', 2, 'THURSDAY', 84);
insert into section_time values(85, 'ONE', 2, 'FRIDAY', 85);
insert into section_time values(86, 'TWO', 2, 'MONDAY', 86);
insert into section_time values(87, 'THREE', 2, 'TUESDAY', 87);
insert into section_time values(88, 'FOUR', 2, 'WEDNESDAY', 88);
insert into section_time values(89, 'FIVE', 2, 'THURSDAY', 89);
insert into section_time values(90, 'SIX', 2, 'FRIDAY', 90);
insert into section_time values(91, 'SEVEN', 2, 'MONDAY', 91);
insert into section_time values(92, 'ONE', 2, 'TUESDAY', 92);
insert into section_time values(93, 'TWO', 2, 'WEDNESDAY', 93);
insert into section_time values(94, 'THREE', 2, 'THURSDAY', 94);
insert into section_time values(95, 'FOUR', 2, 'FRIDAY', 95);
insert into section_time values(96, 'FIVE', 2, 'MONDAY', 96);
insert into section_time values(97, 'SIX', 2, 'TUESDAY', 97);
insert into section_time values(98, 'SEVEN', 2, 'WEDNESDAY', 98);
insert into section_time values(99, 'ONE', 2, 'THURSDAY', 99);
insert into section_time values(100, 'TWO', 2, 'FRIDAY', 82);
insert into section_time values(101, 'THREE', 2, 'MONDAY', 83);
insert into section_time values(102, 'FOUR', 2, 'TUESDAY', 84);
insert into section_time values(103, 'FIVE', 2, 'WEDNESDAY', 85);
insert into section_time values(104, 'SIX', 2, 'THURSDAY', 86);
insert into section_time values(105, 'SEVEN', 2, 'FRIDAY', 87);
insert into section_time values(106, 'ONE', 2, 'MONDAY', 88);
insert into section_time values(107, 'TWO', 2, 'TUESDAY', 89);
insert into section_time values(108, 'THREE', 2, 'WEDNESDAY', 90);
insert into section_time values(109, 'FOUR', 2, 'THURSDAY', 91);
insert into section_time values(110, 'FIVE', 2, 'FRIDAY', 92);
insert into section_time values(111, 'SIX', 2, 'MONDAY', 93);
insert into section_time values(112, 'SEVEN', 2, 'TUESDAY', 94);
insert into section_time values(113, 'ONE', 2, 'WEDNESDAY', 95);
insert into section_time values(114, 'TWO', 2, 'THURSDAY', 96);
insert into section_time values(115, 'THREE', 2, 'FRIDAY', 97);
insert into section_time values(116, 'FOUR', 2, 'MONDAY', 98);
insert into section_time values(117, 'FIVE', 2, 'TUESDAY', 99);
