drop table if exists time_table_list CASCADE;

create table time_table_list (
    id bigint generated by default as identity,
    hash varchar(255) not null,
    course_ids text not null,
    primary key (id)
);

create index time_table_list__hash on time_table_list (hash);
